apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://174.37.17.188:8001
  name: optumera
contexts:
- context:
    cluster: optumera
    namespace: calc-backend
    user: user9
  name: optumera-context
current-context: optumera-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiZWJjMmUyZGNmODk2NDViMmViZGJlZWRlZjA1YzhmOGYxOTJmNDM3OCIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL29wdHVtZXJhLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiI2MTkxMTQ4YjE2ZDdhNWI1MTRjNzQyMGE2NGE2NmZkNSIsImV4cCI6MTU2MDIxNjAyOSwiaWF0IjoxNTYwMTg3MjI5LCJzdWIiOiJhZG1pbiIsInRlYW1Sb2xlTWFwcGluZ3MiOltdfQ.VVJ6M8PTX_2XDYtrivg5fll43citUhTeRyoq77ZT9ONEtKgB7hnEkDcDkZ5MRBvSlZQ-PihIjRfqdITaQo0ihYI0fI8G7YLZUDYxcKWgOvyRuPz1BKxkUYVu6KmZEbXuyeqa9obPUuSTNx04sDynCT4VEB2VUn_OxQiZNP62sVVKqBui8mTd_Xck96bpqEe0YWsTvsROsTj2sXs8-3M7YSQwY_BZPLL2uz-bpAcXr9W0YhM6c3c-oZ0KkMYN9ILqw9jyVGyFx7lEyeCqX2PoHheTX0vGBxv4JPY5qr7nS6x3aB11ntgsOHBLMfeoNHpYhXyeMprZi1alwcXnxAH3yg
- name: optumera-user
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiNzVmMTc2YmNlMTQzZmU5NzMzZWQ5Y2E5YzRjOGE4OTg1M2UzODg3YiIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL29wdHVtZXJhLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiI2MTkxMTQ4YjE2ZDdhNWI1MTRjNzQyMGE2NGE2NmZkNSIsImV4cCI6MTU2MDUzODM4NSwiaWF0IjoxNTYwNTA5NTg1LCJzdWIiOiJhZG1pbiIsInRlYW1Sb2xlTWFwcGluZ3MiOltdfQ.CGrvXdQxFn4FYM54E72I7JgQ90k_jahFIGyHl7sQ7s9MvGd_f6Y6woPNKkUGOztoXagGw7tUU-bMeD2mYE0AkziHy0NkdH3obd3RXz1VWpiBSLSMLFy7QmiclTgmnaaG2A-9ixhaIeXSJAcC1aRCV4WsFj_y95oRVtZvuClBIKt-BIrhRHtruV5nhs3Y-zG6-8OlnL0GCsH2YtMAm6ah4juLMMJFUVgWsrfMw34lxHggAdi2jPlAWiFS03tSs3k1HEW2sPeYqxjavS43X6aSjfNE-pGajMBMK_N9nSI0N0z-jJi92rtdivYMsx-YT0FgZM3PRl2m9LU1B-kWpuaRdA
- name: user9
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiYjA4ZTIwNWRhYjlkYTVlYjU5NmM0NmNjNDM3YWQwMzk3NGRmNTE2YiIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoidXNlcjkiLCJpc3MiOiJodHRwczovL29wdHVtZXJhLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiI2MTkxMTQ4YjE2ZDdhNWI1MTRjNzQyMGE2NGE2NmZkNSIsImV4cCI6MTU2MDg4NDM0MywiaWF0IjoxNTYwODU1NTQzLCJzdWIiOiJ1c2VyOSIsInRlYW1Sb2xlTWFwcGluZ3MiOlsic3lzdGVtOm1hc3RlcnMiXX0.ZjmWMFaqDHWOlkl_COjmbECLqa_OwckIFOrYExxVmg2SNQLzSTmYkx48GK5SVsL-3PK5s4r-6WJ5CU8YVW0oIH3cgwNgKlskb4Miti6Ts9f-QFk50zXiWRI2V8HPz72v08eByAhscE4rdUtI9Bkibz2BRvIOnRpBF9SD2paKyR0layYCdk0gHxSCKqOJXzO-Yua1HvVdUgclU4kijpJAYVPoSSkwz-knXg2v4l0mPv0WOgTm_b0GUDnvXy2JEUmJpRInAtin816G0qn95-4Wg4i54NUTjKy7KWFrAxcbDkHXNvNVtVn7RUbDUP6tdIITLUZKe4P85PMIMIBgo6HStA
